# -*- coding: utf-8 -*-
"""Psoriasis vs eczema.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mdFvqnFjJt0jTeb8RYE19EnYiHyTCIZM
"""

from google.colab import files
uploaded = files.upload()  # select psoriasis_eczema_project.zip from your computer

import zipfile

with zipfile.ZipFile("psoriasis_eczema_project.zip", "r") as zip_ref:
    zip_ref.extractall()

!ls -R

# Commented out IPython magic to ensure Python compatibility.
# %cd psoriasis_eczema_project

!ls

!pip install -q streamlit pyngrok

!pip install -q kaggle
!kaggle datasets download -d ismailpromus/skin-diseases-image-dataset
!unzip -q skin-diseases-image-dataset.zip -d raw_source

!find raw_source -maxdepth 2 -type d

import shutil, os
os.makedirs("raw_data/psoriasis", exist_ok=True)
os.makedirs("raw_data/eczema", exist_ok=True)

# Adjust these source paths to match what step 4 printed
print(shutil.copytree("raw_source/IMG_CLASSES/7. Psoriasis pictures Lichen Planus and related diseases - 2k", "raw_data/psoriasis", dirs_exist_ok=True))
print(shutil.copytree("raw_source/IMG_CLASSES/1. Eczema 1677", "raw_data/eczema", dirs_exist_ok=True))

"""Split into train and test"""

!python split_dataset.py --raw_dir raw_data --out_dir data --train 0.7 --val 0.15 --test 0.15

"""Train the model"""

!python train.py --epochs 15 --fine_tune --fine_tune_epochs 10 --batch_size 32

"""Evaluate and review resuklt"""

!python evaluate.py --model_path model/psoriasis_eczema_model.keras

"""Display the plot"""

from IPython.display import Image, display
display(Image("outputs/confusion_matrix.png"))
display(Image("outputs/roc_curve.png"))
display(Image("outputs/phase1_history.png"))

with open("outputs/classification_report.txt") as f:
    print(f.read())

from pyngrok import ngrok

# Get a free authtoken at https://dashboard.ngrok.com/get-started/your-authtoken
ngrok.set_auth_token("3GxuoN20bEUIMmTLUd6rRtZkMSu_512X7oH3sXM2n4cxj4Tue")

get_ipython().system_raw('streamlit run app.py --server.port 8501 &')
public_url = ngrok.connect(8501)
print(public_url)



"""Saving the trained model to drive"""

from google.colab import drive
drive.mount('/content/drive')

!mkdir -p /content/drive/MyDrive/psoriasis_eczema_backup
!cp -r model outputs data/train data/val data/test /content/drive/MyDrive/psoriasis_eczema_backup/

# Step 12 — Download the trained model + results to your computer
from google.colab import files
!zip -rq trained_outputs.zip model outputs
files.download("trained_outputs.zip")

"""Pushing to gihub"""

!git config --global user.email "utomobongdduff@gmail.com"
!git config --global user.name "Duffutomobong"

!git init
!git add .
!git commit -m "Initial commit: Psoriasis vs Eczema classifier"